"""add savings goal completion state

Revision ID: d4850cc5332f
Revises: 5d55a6f6dc9d
Create Date: 2026-09-18 14:11:32.374699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4850cc5332f'
down_revision: Union[str, Sequence[str], None] = '5d55a6f6dc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goals', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_goals', 'is_completed')
    # ### end Alembic commands ###
